import torch
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--dataset_name", type=str, default="cifar-10")
parser.add_argument("--data_dir", type=str, default="../../../sphere-encoder-main/workspace/datasets")
parser.add_argument("--image_size", type=int, default=32)
parser.add_argument("--latent_dim", type=int, default=768) 
parser.add_argument("--hidden_dim", type=int, default=768)   
parser.add_argument("--cond_dim", type=int, default=256)     
parser.add_argument("--num_layers", type=int, default=12)    
parser.add_argument("--patch_size", type=int, default=4)     
parser.add_argument("--batch_size", type=int, default=256)   
parser.add_argument("--lr", type=float, default=5e-4)        
parser.add_argument("--epochs", type=int, default=100)
parser.add_argument("--warmup_epochs", type=int, default=5)
parser.add_argument("--dropout", type=float, default=0.1)
parser.add_argument("--null_chance", type=float, default=0.1)
parser.add_argument("--noise_level", type=float, default=0.10, help="Spherifying perturbation variance magnitude.")
parser.add_argument("--patience", type=int, default=20, help="Early stopping evaluation epochs window threshold limit.")
parser.add_argument("--num_classes", type=int, default=20)
args = parser.parse_args()

c = torch.load("workspace/best_spherical_autoencoder.pt")
torch.save({"autoencoder": c, "args": args}, "workspace/best_spherical_autoencoder.pt")
